# Generated by Django 4.2 on 2024-07-01 10:57

from django.db import migrations, models
import django.db.models.deletion
import ultrasaga.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nif', models.CharField(max_length=8, validators=[ultrasaga.models.valida_nif])),
                ('nif_titular', models.CharField(max_length=8, validators=[ultrasaga.models.valida_nif])),
                ('codi_centre', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Estudi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('codi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('codi', models.CharField(max_length=8)),
                ('estudi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudis', to='ultrasaga.estudi')),
            ],
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('codi', models.CharField(max_length=8)),
                ('duracio', models.IntegerField()),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ufs', to='ultrasaga.modul')),
            ],
        ),
    ]
