# Generated by Django 4.2 on 2024-07-01 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasaga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uf',
            name='uf',
        ),
        migrations.AddField(
            model_name='uf',
            name='ects',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uf',
            name='modul',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='uf_moduls', to='ultrasaga.modul'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat_aprenentatge', models.TextField()),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ra_ufs', to='ultrasaga.uf')),
            ],
        ),
        migrations.CreateModel(
            name='Contingut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contingut', models.TextField()),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contingut_ufs', to='ultrasaga.uf')),
            ],
        ),
        migrations.CreateModel(
            name='Ca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteri_avaluacio', models.TextField()),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_ufs', to='ultrasaga.uf')),
            ],
        ),
    ]
