# Generated by Django 4.2 on 2024-07-01 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasaga', '0002_remove_uf_uf_uf_ects_uf_modul_ra_contingut_ca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uf',
            name='modul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moduls', to='ultrasaga.modul'),
        ),
    ]
