# Generated by Django 4.2 on 2024-07-01 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasaga', '0003_alter_uf_modul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uf',
            name='ects',
        ),
    ]
