# Generated by Django 4.2 on 2024-07-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasaga', '0005_uf_ects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ca',
            name='uf',
        ),
        migrations.RemoveField(
            model_name='contingut',
            name='uf',
        ),
        migrations.RemoveField(
            model_name='modul',
            name='estudi',
        ),
        migrations.RemoveField(
            model_name='ra',
            name='uf',
        ),
        migrations.RemoveField(
            model_name='uf',
            name='modul',
        ),
    ]
