# Generated by Django 4.2 on 2024-07-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasaga', '0006_remove_ca_uf_remove_contingut_uf_remove_modul_estudi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudi',
            name='normativa',
            field=models.TextField(null=True),
        ),
    ]
