# Generated by Django 4.2 on 2024-07-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasaga', '0007_estudi_normativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudi',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
