# Generated by Django 4.2 on 2024-07-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasaga', '0010_remove_modul_codi_modul_estudi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modul',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
