# Generated by Django 4.2 on 2024-07-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasaga', '0011_alter_modul_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modul',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
