# Generated by Django 4.2 on 2024-07-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasaga', '0012_alter_modul_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='modul',
            name='codi',
            field=models.CharField(default='valorperdefecte', max_length=8),
        ),
    ]
