# Generated by Django 4.2 on 2024-07-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasaga', '0013_modul_codi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modul',
            name='codi',
            field=models.CharField(default='00000001', max_length=8),
        ),
    ]
